spring.application.name=radsan-be

spring.datasource.url=jdbc:postgresql://localhost:5432/radsan_db
spring.datasource.username=postgres
spring.datasource.password=Janu8231

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8082
